version: 2
jobs:
  build:
    docker:
      - image: cypress/base:14.16.0
    working_directory: ~/app
    periodical:
      triggers:
        - schedule:
            cron: "0,31 * * * *"
            filters:
              branches:
                only:
                  - main
    steps:
      - run:
          name: Install Dependencies
          command: npm ci
      - run: $(npm bin)/cypress run --record --key 2e49e6b5-c595-4b08-8024-5fd03119f596
